appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OtkrNtlWJH9ZHYR8rLDccUkf3OqPhzgJiH9wR+JWwyqVLsK3UYmo64YnLKj9wSj0QIhBJM2PzKwkQ69pTLc3ejILZsYtVOQuknwIf7HwSutBp0UgoTtDZq9AvXIDVjmuul/Hn/pytFEvvS8spfm3y06MtccFRdqvP4vQPgQU50UMnJR+vDmZ8+oaryTEnbtjw6GFepJr2hv3pinjgkCnCKLzclIzdTBaKKtnSq3tZXdyqKyQ7DV/fSUauKQrsQSMCVi98jhLbPpwkaiXLpahFZCPfe4F2zZJVTXh3yBE81rpCTGUPnI+2v1RRFwKdh3bzxrv4WBcNjCWWU1Waaj2akmiGw6xY9kjpUHUKTxIKJg2rpd0yuondoBAX/+VeRJEl+9WIXclXHlWhdPeEbLbT8HkH57R6HgyVONmMzpWaunoJ0/PL2zWwGo55qIQgJQYxsmvdxh4Bhhpz0XiyW6zONoYnkstE28ePf42fcAAtfV4ji4INWF3PqppD4KreO0nnee+8Vyc1bYjSHZkT+K9XxpyolOmKGVjDnZekJf25ob3Nmq31TyTTtnJ9B2UJ2HezxDv03ssViOH65phmFegha2/lhwfCYRpw+MNfa+ebVp/+J+L8GieZCfFxDFvWW+vJ0eMFNXXAa7CmcBTYA0d7k/Yrb/iFlOc5VQ/Oyh4314=}
